/**
 * __PRODUCT_NAME__ - Main Process
 * Generated by Pseudo Science Fiction Compile Manager
 * 
 * This is a COMPILED PRODUCT using custom catalog.
 * Theme colors are baked in from Core-CE settings.
 */

const { app, BrowserWindow, ipcMain, shell, dialog, screen } = require('electron');
const path = require('path');
const fs = require('fs');

// ============================================================================
// Path Configuration
// ============================================================================

const appDir = __dirname;
const modelsDir = path.join(appDir, '..', 'models');
const settingsPath = path.join(modelsDir, 'psf-settings.json');
const catalogPath = path.join(appDir, 'product-catalog.json');

// ============================================================================
// Window Management
// ============================================================================

let mainWindow = null;

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function resolveSafeBounds({ width, height, minWidth = 640, minHeight = 520 }) {
  const workArea = screen.getPrimaryDisplay().workArea || { x: 0, y: 0, width: 1280, height: 800 };
  const safeWidth = Math.max(420, Number(workArea.width || 1280) - 24);
  const safeHeight = Math.max(360, Number(workArea.height || 800) - 32);
  const finalWidth = clamp(Number(width) || 1000, 420, safeWidth);
  const finalHeight = clamp(Number(height) || 700, 360, safeHeight);
  return {
    width: finalWidth,
    height: finalHeight,
    minWidth: clamp(Number(minWidth) || 640, 420, finalWidth),
    minHeight: clamp(Number(minHeight) || 520, 360, finalHeight),
    x: Number(workArea.x || 0) + Math.max(0, Math.floor((safeWidth - finalWidth) / 2)),
    y: Number(workArea.y || 0) + Math.max(0, Math.floor((safeHeight - finalHeight) / 2))
  };
}

// ============================================================================
// BMOC-Lite Session Manager (Module Scope for cleanup access)
// ============================================================================

const sessionManager = require('./session-manager-standard.js');

function createWindow() {
  const bounds = resolveSafeBounds({
    width: 1400,
    height: 900,
    minWidth: 1024,
    minHeight: 700
  });
  mainWindow = new BrowserWindow({
    ...bounds,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true
    },
    icon: path.join(__dirname, 'assets', 'icon.png'),
    title: '__PRODUCT_NAME__'
  });

  mainWindow.loadFile('src/index.html');
  
  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

// ============================================================================
// Settings & Theme Management
// ============================================================================

function loadSettings() {
  try {
    if (fs.existsSync(settingsPath)) {
      return JSON.parse(fs.readFileSync(settingsPath, 'utf-8'));
    }
  } catch (err) {
    console.error('[Settings] Error loading settings:', err.message);
  }
  return {};
}

function saveSettings(settings) {
  try {
    fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
    fs.writeFileSync(settingsPath, JSON.stringify(settings, null, 2), 'utf-8');
    return { success: true };
  } catch (err) {
    console.error('[Settings] Error saving settings:', err.message);
    return { success: false, error: err.message };
  }
}

// ============================================================================
// IPC Handlers
// ============================================================================

